// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoBuff.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ro.Mpp2024.Protobuffprotocol {

  /// <summary>Holder for reflection information generated from ProtoBuff.proto</summary>
  public static partial class ProtoBuffReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoBuff.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoBuffReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0J1ZmYucHJvdG8SHHJvLm1wcDIwMjQucHJvdG9idWZmcHJvdG9j",
            "b2waH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8iKgoEVXNlchIQ",
            "Cgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJxCgRUcmlwEgoK",
            "AmlkGAEgASgDEjEKDWRlcGFydHVyZVRpbWUYAiABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wEhUKDW51bWJlck9mU2VhdHMYAyABKAUSEwoLZGVz",
            "dGluYXRpb24YBCABKAkiXgoHQm9va2luZxISCgpjbGllbnROYW1lGAEgASgJ",
            "EjAKBHRyaXAYAiABKAsyIi5yby5tcHAyMDI0LnByb3RvYnVmZnByb3RvY29s",
            "LlRyaXASDQoFc2VhdHMYAyADKAUiNQoLQm9va2luZ1NlYXQSEgoKc2VhdE51",
            "bWJlchgBIAEoBRISCgpjbGllbnROYW1lGAIgASgJInsKCVRyaXBTZWF0cxIO",
            "CgZ0cmlwSWQYASABKAMSEwoLZGVzdGluYXRpb24YAiABKAkSMQoNZGVwYXJ0",
            "dXJlVGltZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFgoO",
            "YXZhaWxhYmxlU2VhdHMYBCABKAUi1gMKB1JlcXVlc3QSOAoEdHlwZRgBIAEo",
            "DjIqLnJvLm1wcDIwMjQucHJvdG9idWZmcHJvdG9jb2wuUmVxdWVzdC5UeXBl",
            "EjIKBHVzZXIYAiABKAsyIi5yby5tcHAyMDI0LnByb3RvYnVmZnByb3RvY29s",
            "LlVzZXJIABIyCgR0cmlwGAMgASgLMiIucm8ubXBwMjAyNC5wcm90b2J1ZmZw",
            "cm90b2NvbC5UcmlwSAASOAoHYm9va2luZxgEIAEoCzIlLnJvLm1wcDIwMjQu",
            "cHJvdG9idWZmcHJvdG9jb2wuQm9va2luZ0gAEjwKCXRyaXBTZWF0cxgFIAEo",
            "CzInLnJvLm1wcDIwMjQucHJvdG9idWZmcHJvdG9jb2wuVHJpcFNlYXRzSAAS",
            "EgoIdXNlcm5hbWUYBiABKAlIABIMCgJpZBgHIAEoA0gAIoMBCgRUeXBlEgsK",
            "B1Vua25vd24QABIJCgVMb2dpbhABEgoKBkxvZ291dBACEgsKB0dldFRyaXAQ",
            "AxIVChFHZXRUcmlwc1dpdGhTZWF0cxAEEhYKEkdldEJvb2tpbmdzRm9yVHJp",
            "cBAFEg4KCkFkZEJvb2tpbmcQBhILCgdHZXRVc2VyEAdCCQoHcGF5bG9hZCKx",
            "AwoIUmVzcG9uc2USOQoEdHlwZRgBIAEoDjIrLnJvLm1wcDIwMjQucHJvdG9i",
            "dWZmcHJvdG9jb2wuUmVzcG9uc2UuVHlwZRINCgVlcnJvchgCIAEoCRIwCgR1",
            "c2VyGAMgASgLMiIucm8ubXBwMjAyNC5wcm90b2J1ZmZwcm90b2NvbC5Vc2Vy",
            "EjYKBXRyaXBzGAQgAygLMicucm8ubXBwMjAyNC5wcm90b2J1ZmZwcm90b2Nv",
            "bC5UcmlwU2VhdHMSOwoIYm9va2luZ3MYBSADKAsyKS5yby5tcHAyMDI0LnBy",
            "b3RvYnVmZnByb3RvY29sLkJvb2tpbmdTZWF0EjAKBHRyaXAYBiABKAsyIi5y",
            "by5tcHAyMDI0LnByb3RvYnVmZnByb3RvY29sLlRyaXAigQEKBFR5cGUSCwoH",
            "VW5rbm93bhAAEgYKAk9rEAESCQoFRXJyb3IQAhILCgdHZXRVc2VyEAMSFQoR",
            "R2V0VHJpcHNXaXRoU2VhdHMQBBIWChJHZXRCb29raW5nc0ZvclRyaXAQBRIL",
            "CgdHZXRUcmlwEAYSEAoMU2VhdHNVcGRhdGVkEAdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.User), global::Ro.Mpp2024.Protobuffprotocol.User.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.Trip), global::Ro.Mpp2024.Protobuffprotocol.Trip.Parser, new[]{ "Id", "DepartureTime", "NumberOfSeats", "Destination" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.Booking), global::Ro.Mpp2024.Protobuffprotocol.Booking.Parser, new[]{ "ClientName", "Trip", "Seats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.BookingSeat), global::Ro.Mpp2024.Protobuffprotocol.BookingSeat.Parser, new[]{ "SeatNumber", "ClientName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.TripSeats), global::Ro.Mpp2024.Protobuffprotocol.TripSeats.Parser, new[]{ "TripId", "Destination", "DepartureTime", "AvailableSeats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.Request), global::Ro.Mpp2024.Protobuffprotocol.Request.Parser, new[]{ "Type", "User", "Trip", "Booking", "TripSeats", "Username", "Id" }, new[]{ "Payload" }, new[]{ typeof(global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protobuffprotocol.Response), global::Ro.Mpp2024.Protobuffprotocol.Response.Parser, new[]{ "Type", "Error", "User", "Trips", "Bookings", "Trip" }, null, new[]{ typeof(global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class User : pb::IMessage<User>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<User> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User(User other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User Clone() {
      return new User(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as User);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(User other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(User other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Trip : pb::IMessage<Trip>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Trip> _parser = new pb::MessageParser<Trip>(() => new Trip());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Trip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip(Trip other) : this() {
      id_ = other.id_;
      departureTime_ = other.departureTime_ != null ? other.departureTime_.Clone() : null;
      numberOfSeats_ = other.numberOfSeats_;
      destination_ = other.destination_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip Clone() {
      return new Trip(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "departureTime" field.</summary>
    public const int DepartureTimeFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp departureTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DepartureTime {
      get { return departureTime_; }
      set {
        departureTime_ = value;
      }
    }

    /// <summary>Field number for the "numberOfSeats" field.</summary>
    public const int NumberOfSeatsFieldNumber = 3;
    private int numberOfSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfSeats {
      get { return numberOfSeats_; }
      set {
        numberOfSeats_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 4;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Trip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Trip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(DepartureTime, other.DepartureTime)) return false;
      if (NumberOfSeats != other.NumberOfSeats) return false;
      if (Destination != other.Destination) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (departureTime_ != null) hash ^= DepartureTime.GetHashCode();
      if (NumberOfSeats != 0) hash ^= NumberOfSeats.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (departureTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DepartureTime);
      }
      if (NumberOfSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Destination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (departureTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DepartureTime);
      }
      if (NumberOfSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Destination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (departureTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepartureTime);
      }
      if (NumberOfSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfSeats);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Trip other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.departureTime_ != null) {
        if (departureTime_ == null) {
          DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DepartureTime.MergeFrom(other.DepartureTime);
      }
      if (other.NumberOfSeats != 0) {
        NumberOfSeats = other.NumberOfSeats;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (departureTime_ == null) {
              DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepartureTime);
            break;
          }
          case 24: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
          case 34: {
            Destination = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (departureTime_ == null) {
              DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepartureTime);
            break;
          }
          case 24: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
          case 34: {
            Destination = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Booking : pb::IMessage<Booking>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Booking> _parser = new pb::MessageParser<Booking>(() => new Booking());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Booking> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking(Booking other) : this() {
      clientName_ = other.clientName_;
      trip_ = other.trip_ != null ? other.trip_.Clone() : null;
      seats_ = other.seats_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Booking Clone() {
      return new Booking(this);
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 1;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 2;
    private global::Ro.Mpp2024.Protobuffprotocol.Trip trip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Trip Trip {
      get { return trip_; }
      set {
        trip_ = value;
      }
    }

    /// <summary>Field number for the "seats" field.</summary>
    public const int SeatsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_seats_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> seats_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Seats {
      get { return seats_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Booking);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Booking other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientName != other.ClientName) return false;
      if (!object.Equals(Trip, other.Trip)) return false;
      if(!seats_.Equals(other.seats_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (trip_ != null) hash ^= Trip.GetHashCode();
      hash ^= seats_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (trip_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Trip);
      }
      seats_.WriteTo(output, _repeated_seats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (trip_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Trip);
      }
      seats_.WriteTo(ref output, _repeated_seats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (trip_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
      }
      size += seats_.CalculateSize(_repeated_seats_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Booking other) {
      if (other == null) {
        return;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      if (other.trip_ != null) {
        if (trip_ == null) {
          Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
        }
        Trip.MergeFrom(other.Trip);
      }
      seats_.Add(other.seats_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            if (trip_ == null) {
              Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
          case 26:
          case 24: {
            seats_.AddEntriesFrom(input, _repeated_seats_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            if (trip_ == null) {
              Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
          case 26:
          case 24: {
            seats_.AddEntriesFrom(ref input, _repeated_seats_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BookingSeat : pb::IMessage<BookingSeat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BookingSeat> _parser = new pb::MessageParser<BookingSeat>(() => new BookingSeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BookingSeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BookingSeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BookingSeat(BookingSeat other) : this() {
      seatNumber_ = other.seatNumber_;
      clientName_ = other.clientName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BookingSeat Clone() {
      return new BookingSeat(this);
    }

    /// <summary>Field number for the "seatNumber" field.</summary>
    public const int SeatNumberFieldNumber = 1;
    private int seatNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeatNumber {
      get { return seatNumber_; }
      set {
        seatNumber_ = value;
      }
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 2;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BookingSeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BookingSeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeatNumber != other.SeatNumber) return false;
      if (ClientName != other.ClientName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeatNumber != 0) hash ^= SeatNumber.GetHashCode();
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeatNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeatNumber);
      }
      if (ClientName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeatNumber != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeatNumber);
      }
      if (ClientName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeatNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeatNumber);
      }
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BookingSeat other) {
      if (other == null) {
        return;
      }
      if (other.SeatNumber != 0) {
        SeatNumber = other.SeatNumber;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeatNumber = input.ReadInt32();
            break;
          }
          case 18: {
            ClientName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeatNumber = input.ReadInt32();
            break;
          }
          case 18: {
            ClientName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TripSeats : pb::IMessage<TripSeats>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TripSeats> _parser = new pb::MessageParser<TripSeats>(() => new TripSeats());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TripSeats> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripSeats() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripSeats(TripSeats other) : this() {
      tripId_ = other.tripId_;
      destination_ = other.destination_;
      departureTime_ = other.departureTime_ != null ? other.departureTime_.Clone() : null;
      availableSeats_ = other.availableSeats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripSeats Clone() {
      return new TripSeats(this);
    }

    /// <summary>Field number for the "tripId" field.</summary>
    public const int TripIdFieldNumber = 1;
    private long tripId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TripId {
      get { return tripId_; }
      set {
        tripId_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 2;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "departureTime" field.</summary>
    public const int DepartureTimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp departureTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DepartureTime {
      get { return departureTime_; }
      set {
        departureTime_ = value;
      }
    }

    /// <summary>Field number for the "availableSeats" field.</summary>
    public const int AvailableSeatsFieldNumber = 4;
    private int availableSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvailableSeats {
      get { return availableSeats_; }
      set {
        availableSeats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TripSeats);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TripSeats other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TripId != other.TripId) return false;
      if (Destination != other.Destination) return false;
      if (!object.Equals(DepartureTime, other.DepartureTime)) return false;
      if (AvailableSeats != other.AvailableSeats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TripId != 0L) hash ^= TripId.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (departureTime_ != null) hash ^= DepartureTime.GetHashCode();
      if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TripId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TripId);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (departureTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DepartureTime);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AvailableSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TripId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TripId);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Destination);
      }
      if (departureTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DepartureTime);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AvailableSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TripId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TripId);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (departureTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepartureTime);
      }
      if (AvailableSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TripSeats other) {
      if (other == null) {
        return;
      }
      if (other.TripId != 0L) {
        TripId = other.TripId;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.departureTime_ != null) {
        if (departureTime_ == null) {
          DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DepartureTime.MergeFrom(other.DepartureTime);
      }
      if (other.AvailableSeats != 0) {
        AvailableSeats = other.AvailableSeats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TripId = input.ReadInt64();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            if (departureTime_ == null) {
              DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepartureTime);
            break;
          }
          case 32: {
            AvailableSeats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TripId = input.ReadInt64();
            break;
          }
          case 18: {
            Destination = input.ReadString();
            break;
          }
          case 26: {
            if (departureTime_ == null) {
              DepartureTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DepartureTime);
            break;
          }
          case 32: {
            AvailableSeats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          User = other.User.Clone();
          break;
        case PayloadOneofCase.Trip:
          Trip = other.Trip.Clone();
          break;
        case PayloadOneofCase.Booking:
          Booking = other.Booking.Clone();
          break;
        case PayloadOneofCase.TripSeats:
          TripSeats = other.TripSeats.Clone();
          break;
        case PayloadOneofCase.Username:
          Username = other.Username;
          break;
        case PayloadOneofCase.Id:
          Id = other.Id;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type type_ = global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.User User {
      get { return payloadCase_ == PayloadOneofCase.User ? (global::Ro.Mpp2024.Protobuffprotocol.User) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
      }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Trip Trip {
      get { return payloadCase_ == PayloadOneofCase.Trip ? (global::Ro.Mpp2024.Protobuffprotocol.Trip) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Trip;
      }
    }

    /// <summary>Field number for the "booking" field.</summary>
    public const int BookingFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Booking Booking {
      get { return payloadCase_ == PayloadOneofCase.Booking ? (global::Ro.Mpp2024.Protobuffprotocol.Booking) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Booking;
      }
    }

    /// <summary>Field number for the "tripSeats" field.</summary>
    public const int TripSeatsFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.TripSeats TripSeats {
      get { return payloadCase_ == PayloadOneofCase.TripSeats ? (global::Ro.Mpp2024.Protobuffprotocol.TripSeats) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TripSeats;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return HasUsername ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Username;
      }
    }
    /// <summary>Gets whether the "username" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUsername {
      get { return payloadCase_ == PayloadOneofCase.Username; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "username" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUsername() {
      if (HasUsername) {
        ClearPayload();
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return HasId ? (long) payload_ : 0L; }
      set {
        payload_ = value;
        payloadCase_ = PayloadOneofCase.Id;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return payloadCase_ == PayloadOneofCase.Id; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      if (HasId) {
        ClearPayload();
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      User = 2,
      Trip = 3,
      Booking = 4,
      TripSeats = 5,
      Username = 6,
      Id = 7,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Trip, other.Trip)) return false;
      if (!object.Equals(Booking, other.Booking)) return false;
      if (!object.Equals(TripSeats, other.TripSeats)) return false;
      if (Username != other.Username) return false;
      if (Id != other.Id) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Trip) hash ^= Trip.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Booking) hash ^= Booking.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TripSeats) hash ^= TripSeats.GetHashCode();
      if (HasUsername) hash ^= Username.GetHashCode();
      if (HasId) hash ^= Id.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Trip) {
        output.WriteRawTag(26);
        output.WriteMessage(Trip);
      }
      if (payloadCase_ == PayloadOneofCase.Booking) {
        output.WriteRawTag(34);
        output.WriteMessage(Booking);
      }
      if (payloadCase_ == PayloadOneofCase.TripSeats) {
        output.WriteRawTag(42);
        output.WriteMessage(TripSeats);
      }
      if (HasUsername) {
        output.WriteRawTag(50);
        output.WriteString(Username);
      }
      if (HasId) {
        output.WriteRawTag(56);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Trip) {
        output.WriteRawTag(26);
        output.WriteMessage(Trip);
      }
      if (payloadCase_ == PayloadOneofCase.Booking) {
        output.WriteRawTag(34);
        output.WriteMessage(Booking);
      }
      if (payloadCase_ == PayloadOneofCase.TripSeats) {
        output.WriteRawTag(42);
        output.WriteMessage(TripSeats);
      }
      if (HasUsername) {
        output.WriteRawTag(50);
        output.WriteString(Username);
      }
      if (HasId) {
        output.WriteRawTag(56);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (payloadCase_ == PayloadOneofCase.Trip) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
      }
      if (payloadCase_ == PayloadOneofCase.Booking) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Booking);
      }
      if (payloadCase_ == PayloadOneofCase.TripSeats) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TripSeats);
      }
      if (HasUsername) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          if (User == null) {
            User = new global::Ro.Mpp2024.Protobuffprotocol.User();
          }
          User.MergeFrom(other.User);
          break;
        case PayloadOneofCase.Trip:
          if (Trip == null) {
            Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
          }
          Trip.MergeFrom(other.Trip);
          break;
        case PayloadOneofCase.Booking:
          if (Booking == null) {
            Booking = new global::Ro.Mpp2024.Protobuffprotocol.Booking();
          }
          Booking.MergeFrom(other.Booking);
          break;
        case PayloadOneofCase.TripSeats:
          if (TripSeats == null) {
            TripSeats = new global::Ro.Mpp2024.Protobuffprotocol.TripSeats();
          }
          TripSeats.MergeFrom(other.TripSeats);
          break;
        case PayloadOneofCase.Username:
          Username = other.Username;
          break;
        case PayloadOneofCase.Id:
          Id = other.Id;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2024.Protobuffprotocol.User subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.User();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            global::Ro.Mpp2024.Protobuffprotocol.Trip subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            if (payloadCase_ == PayloadOneofCase.Trip) {
              subBuilder.MergeFrom(Trip);
            }
            input.ReadMessage(subBuilder);
            Trip = subBuilder;
            break;
          }
          case 34: {
            global::Ro.Mpp2024.Protobuffprotocol.Booking subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.Booking();
            if (payloadCase_ == PayloadOneofCase.Booking) {
              subBuilder.MergeFrom(Booking);
            }
            input.ReadMessage(subBuilder);
            Booking = subBuilder;
            break;
          }
          case 42: {
            global::Ro.Mpp2024.Protobuffprotocol.TripSeats subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.TripSeats();
            if (payloadCase_ == PayloadOneofCase.TripSeats) {
              subBuilder.MergeFrom(TripSeats);
            }
            input.ReadMessage(subBuilder);
            TripSeats = subBuilder;
            break;
          }
          case 50: {
            Username = input.ReadString();
            break;
          }
          case 56: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protobuffprotocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2024.Protobuffprotocol.User subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.User();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            global::Ro.Mpp2024.Protobuffprotocol.Trip subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            if (payloadCase_ == PayloadOneofCase.Trip) {
              subBuilder.MergeFrom(Trip);
            }
            input.ReadMessage(subBuilder);
            Trip = subBuilder;
            break;
          }
          case 34: {
            global::Ro.Mpp2024.Protobuffprotocol.Booking subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.Booking();
            if (payloadCase_ == PayloadOneofCase.Booking) {
              subBuilder.MergeFrom(Booking);
            }
            input.ReadMessage(subBuilder);
            Booking = subBuilder;
            break;
          }
          case 42: {
            global::Ro.Mpp2024.Protobuffprotocol.TripSeats subBuilder = new global::Ro.Mpp2024.Protobuffprotocol.TripSeats();
            if (payloadCase_ == PayloadOneofCase.TripSeats) {
              subBuilder.MergeFrom(TripSeats);
            }
            input.ReadMessage(subBuilder);
            TripSeats = subBuilder;
            break;
          }
          case 50: {
            Username = input.ReadString();
            break;
          }
          case 56: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetTrip")] GetTrip = 3,
        [pbr::OriginalName("GetTripsWithSeats")] GetTripsWithSeats = 4,
        [pbr::OriginalName("GetBookingsForTrip")] GetBookingsForTrip = 5,
        [pbr::OriginalName("AddBooking")] AddBooking = 6,
        [pbr::OriginalName("GetUser")] GetUser = 7,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protobuffprotocol.ProtoBuffReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      trips_ = other.trips_.Clone();
      bookings_ = other.bookings_.Clone();
      trip_ = other.trip_ != null ? other.trip_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type type_ = global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 3;
    private global::Ro.Mpp2024.Protobuffprotocol.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "trips" field.</summary>
    public const int TripsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ro.Mpp2024.Protobuffprotocol.TripSeats> _repeated_trips_codec
        = pb::FieldCodec.ForMessage(34, global::Ro.Mpp2024.Protobuffprotocol.TripSeats.Parser);
    private readonly pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.TripSeats> trips_ = new pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.TripSeats>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.TripSeats> Trips {
      get { return trips_; }
    }

    /// <summary>Field number for the "bookings" field.</summary>
    public const int BookingsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ro.Mpp2024.Protobuffprotocol.BookingSeat> _repeated_bookings_codec
        = pb::FieldCodec.ForMessage(42, global::Ro.Mpp2024.Protobuffprotocol.BookingSeat.Parser);
    private readonly pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.BookingSeat> bookings_ = new pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.BookingSeat>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ro.Mpp2024.Protobuffprotocol.BookingSeat> Bookings {
      get { return bookings_; }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 6;
    private global::Ro.Mpp2024.Protobuffprotocol.Trip trip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protobuffprotocol.Trip Trip {
      get { return trip_; }
      set {
        trip_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(User, other.User)) return false;
      if(!trips_.Equals(other.trips_)) return false;
      if(!bookings_.Equals(other.bookings_)) return false;
      if (!object.Equals(Trip, other.Trip)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      hash ^= trips_.GetHashCode();
      hash ^= bookings_.GetHashCode();
      if (trip_ != null) hash ^= Trip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (user_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      trips_.WriteTo(output, _repeated_trips_codec);
      bookings_.WriteTo(output, _repeated_bookings_codec);
      if (trip_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Trip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (user_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      trips_.WriteTo(ref output, _repeated_trips_codec);
      bookings_.WriteTo(ref output, _repeated_bookings_codec);
      if (trip_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Trip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      size += trips_.CalculateSize(_repeated_trips_codec);
      size += bookings_.CalculateSize(_repeated_bookings_codec);
      if (trip_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Ro.Mpp2024.Protobuffprotocol.User();
        }
        User.MergeFrom(other.User);
      }
      trips_.Add(other.trips_);
      bookings_.Add(other.bookings_);
      if (other.trip_ != null) {
        if (trip_ == null) {
          Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
        }
        Trip.MergeFrom(other.Trip);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (user_ == null) {
              User = new global::Ro.Mpp2024.Protobuffprotocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 34: {
            trips_.AddEntriesFrom(input, _repeated_trips_codec);
            break;
          }
          case 42: {
            bookings_.AddEntriesFrom(input, _repeated_bookings_codec);
            break;
          }
          case 50: {
            if (trip_ == null) {
              Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protobuffprotocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (user_ == null) {
              User = new global::Ro.Mpp2024.Protobuffprotocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 34: {
            trips_.AddEntriesFrom(ref input, _repeated_trips_codec);
            break;
          }
          case 42: {
            bookings_.AddEntriesFrom(ref input, _repeated_bookings_codec);
            break;
          }
          case 50: {
            if (trip_ == null) {
              Trip = new global::Ro.Mpp2024.Protobuffprotocol.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("GetUser")] GetUser = 3,
        [pbr::OriginalName("GetTripsWithSeats")] GetTripsWithSeats = 4,
        [pbr::OriginalName("GetBookingsForTrip")] GetBookingsForTrip = 5,
        [pbr::OriginalName("GetTrip")] GetTrip = 6,
        [pbr::OriginalName("SeatsUpdated")] SeatsUpdated = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
